### PR TITLE
feat: publish debug builds

### PR DESCRIPTION
**Pull request by ArjixWasTaken**
You will need to create a release tag named `debug`, since the action can't do that w/o special perms.

### CODE REVIEW

**Comment by daBroma** [comment]
🤨 checking under Actions is hard?

**Comment by ArjixWasTaken** [comment]
> 🤨 checking under Actions is hard?

you need an account in order to download artifacts

**Comment by daBroma** [comment]
https://nightly.link/zt64/Hyperion/workflows/build-debug/main/app-debug.zip

**Comment by ArjixWasTaken** [comment]
> [nightly.link/zt64/Hyperion/workflows/build-debug/main/app-debug.zip](https://nightly.link/zt64/Hyperion/workflows/build-debug/main/app-debug.zip)

Why should we depend on a third party service?

**Comment by daBroma** [comment]
Either log in to Github or use Nightly.link. No reason to publish anything if it is not stable at all.

**Comment by ArjixWasTaken** [comment]
> Either log in to Github or use Nightly.link. No reason to publish anything if it is not stable at all.

a prerelease with the tag name of "debug" is pretty self explanatory that it is not stable

**Comment by zt64** [comment]
Problem is though that I don't wanna have dozens of releases in this very early stage of development. Once stuff is a little more polished then that's when I'll setup releases but for now nightly.link is fine.

**Comment by ArjixWasTaken** [comment]
> Problem is though that I don't wanna have dozens of releases in this very early stage of development. Once stuff is a little more polished then that's when I'll setup releases but for now nightly.link is fine.

The wouldn't be dozen of releases though, only the latest one would be there, you cant have multiple releases under the same tag

**Comment by DiamondMiner88** [comment]
Me when 5 morbillion tags for every commit
There's no point in making releases for an app that isn't stable

**Pull request closed without merging**
